name: Generate Contribution Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # daily at 00:00 UTC

permissions:
  contents: write          # needed to write to the output branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake (SVG)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: reshinto
          outputs: |
            dist/snake.svg

      - name: Verify file exists (fail fast)
        run: |
          echo "Listing dist/ for debug:"
          ls -la dist || true
          test -f dist/snake.svg || (echo "ERROR: dist/snake.svg not generated" && exit 1)

      - name: Publish to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
